import { resolve } from 'node:path'

export async function generateThemeFlash() {
  const build = await Bun.build({
    entrypoints: [resolve(import.meta.dir, '../src/theme/flash.ts')],
    target: 'browser',
    format: 'iife',
    minify: true,
  })
  if (!build.success) throw new Error(build.logs.join('\n'))
  return `\n      // Generated by scripts/generate-theme-flash.ts — do not edit by hand.\n      ${(await build.outputs[0]!.text()).trim()}\n    `
}

if (import.meta.main) {
  const html = Bun.file(resolve(import.meta.dir, '../index.html'))
  const script = await generateThemeFlash()
  await Bun.write(
    html,
    (await html.text()).replace(
      /(<script data-tau-theme-flash>)[\s\S]*?(<\/script>)/,
      (_, start, end) => `${start}${script}${end}`
    )
  )
}
